version: "2"
services:

  node:
    image: "node:12"
    user: "node"
    working_dir: /var/www/roll
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/var/www/roll
    ports:
      - "3000:3000"
    links:
      - mongo
    command: "npm start"

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"